Mei-K/ec-202110c

package-lock.json, package.json, public/common.css, public/index.html, src/router/index.ts, src/types/Item.ts, src/views/itemDetail.vue
=> 1-4.商品詳細を表示する機能を追加しました。

src/components/Header.vue, src/router/index.ts, src/store/index.ts, src/views/itemList.vue
商品一覧にページングを機能を作成しました。
また、mutationの中のpayload.itemsに変更し、APIから正しく商品一覧を取得できるように訂正しました。
ご確認の程、よろしくお願い致します。
=> 商品一覧にページングを追加、mutationのpayload.itemsを変更しました

src/router/index.ts, src/views/itemList.vue
=> 商品リストから詳細画面へのリンクを修正しました。

src/components/Header.vue, src/router/index.ts, src/store/index.ts, src/views/Home.vue, src/views/itemList.vue
=> Headerファイルのルーティングを修正

src/router/index.ts, src/views/RegisterUser.vue, src/views/loginUser.vue
ログイン機能実装しました。ログイン機能単体のテストは実施済みです。ご確認の程宜しくお願いします。
=> 1-2.ログイン機能実装しました

src/types/OrderItem.ts, src/views/cartList.vue
=> orderItemUnitPriceを表示するメソッドの場所を修正しました。

src/views/itemList.vue
商品検索がしやすいように機能追加しました。
ご確認の程、よろしくお願いします。
=> 商品一覧検索にサジェスト機能を追加しました

package-lock.json, package.json, src/views/RegisterUser.vue
=> 住所取得のメソッド名変更しました

package-lock.json, package.json, src/store/index.ts
=> sessionStorage機能を追加しました。

src/components/Header.vue, src/router/index.ts, src/views/logoutUser.vue
ログアウト機能を再度実装しました。headerのログアウトを押すと、logoutUser.vueに遷移してログアウト処理が実行されます。ご確認の程よろしくお願い致します。
=> 1.2ログアウト機能を実装しました。

src/store/index.ts, src/views/cartList.vue, src/views/itemDetail.vue
=> ショッピングカートに入っている商品を削除する機能を追加しました。

package-lock.json, package.json, src/router/index.ts, src/store/index.ts, src/types/Item.ts, src/types/OrderItem.ts, src/views/OrderFinished.vue, src/views/cartList.vue, src/views/orderConfirm.vue
バリデーションエラー処理はまだ実装してません。
クレジットカード機能もこれから実装します。
=> 注文処理と注文完了ページの作成

src/types/OrderItem.ts, src/views/cartList.vue, src/views/itemDetail.vue
=> 消費税と税込合計金額を表示する機能を実装しました。

src/components/Header.vue, src/store/index.ts, src/views/RegisterUser.vue, src/views/loginUser.vue, src/views/logoutUser.vue
ログイン状態をプラグインを使用して
ログイン状態によって表示させるヘッダーの内容が変わるように
内容を変更しました。
=> ログイン認証フィルターを追加しました。

src/store/index.ts, src/views/itemList.vue
並び順変更機能を実装しました。mutation経由でsortすることでエラーを回避しています。ご確認の程よろしくお願い致します。
=> 並び順変更機能を実装しました

src/views/itemDetail.vue
=> 商品のサイズの初期値を「M」に訂正しました。

src/views/orderConfirm.vue
=> 配達日時を3時間後ではない時間を選択された場合にエラーを表示するように修正しました。

src/views/orderConfirm.vue
=> 入力値が不正な場合にエラーメッセージを表示するように修正しました。

src/views/RegisterUser.vue, src/views/orderConfirm.vue
=> 郵便番号と電話番号の入力値が不正な場合エラーメッセージを表示するように修正しました。

public/index.html, src/store/index.ts, src/types/Item.ts, src/views/itemList.vue
=> いいね機能を実装しました

public/common.css, src/components/Header.vue, src/views/Home.vue, src/views/RegisterUser.vue, src/views/cartList.vue, src/views/contactCompany.vue, src/views/itemList.vue, src/views/loginUser.vue
=> css修正しました。（後もう少しです。）

src/views/OrderHistory.vue, src/views/itemList.vue
=> --並び替え--をおすすめ順に変更

src/views/itemDetail.vue, src/views/orderConfirm.vue
=> 注文を完了できないバグを修正しました。

src/views/itemDetail.vue
=> ラジオボタン、セレクトボックスの色を変更しました。

src/store/index.ts, src/views/OrderHistory.vue
=> 再注文機能実装しました

src/views/orderConfirm.vue
=> css)チェックボックスのいろ変えました

src/views/itemDetail.vue, src/views/itemList.vue
=> いいねボタンの上にカーソルを置いたときに、pointerになるように修正しました。

src/views/RegisterUser.vue, src/views/cartList.vue, src/views/contactCompany.vue, src/views/itemList.vue, src/views/loginAdministrator.vue, src/views/loginUser.vue
=> css、入力欄の背景を統一しました

src/views/OrderHistory.vue, src/views/cartList.vue, src/views/orderConfirm.vue
=> テーブルのCSSを修正しました。

src/types/Order.ts, src/types/OrderItem.ts, src/views/Home.vue, src/views/OrderFinished.vue, src/views/OrderHistory.vue, src/views/RegisterUser.vue, src/views/addNewItem.vue, src/views/cartList.vue, src/views/contactCompany.vue, src/views/itemDetail.vue, src/views/itemList.vue, src/views/loginAdministrator.vue, src/views/loginUser.vue, src/views/logoutUser.vue, src/views/orderConfirm.vue
=> TSDocの修正をしました。

src/views/orderConfirm.vue
=> クレジットカード名義人の姓名の間に半角スペースがあると、エラーが出るバグを修正しました。

src/views/orderConfirm.vue
=> 金額が3桁区切りでコンマが入るように修正しました。
